automatedPythonMarker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
    path('', RedirectView.as_view(url='/questions/', permanent=True)),
]

questions/urls.py
from django.urls import path

from .views import (question_list_view, question_update_view, question_generate_submission_file_view)

app_name = 'questions'

urlpatterns = [
    path('', question_list_view, name='question-list'),
    path('<int:number>/', question_update_view, name='question-update'),
    path('submit', question_generate_submission_file_view, name='question-submit')
]

questions/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from GetOrNoneManager import GetOrNoneManager


class SubQuestionCompositeManager(GetOrNoneManager, models.Manager):
    pass


class QuestionComposite(models.Model):
    number = models.IntegerField()
    description = models.TextField(blank=False, null=False)
    objects = SubQuestionCompositeManager()

    def get_absolute_url(self):
        return reverse("questions:question-update", kwargs={"number": self.number})


class SubQuestionComposite(models.Model):
    question = models.ForeignKey(QuestionComposite, on_delete=models.CASCADE)
    part = models.IntegerField()
    description = models.TextField(blank=False, null=False)
    method_name = models.TextField()
    max_mark = models.IntegerField()
    part_name = models.TextField(blank=False, null=False)
    object = SubQuestionCompositeManager()

questions/forms.py
from django import forms
from .models import Question, SubQuestionComposite


class QuestionForm(forms.ModelForm):
    answer = forms.CharField(
        label='',
        required=True,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Enter Your Answer Here",
                "class": "new-class-name two",
                "rows": 20,
                "cols": 120
            }
        )
    )

    class Meta:
        model = SubQuestionComposite
        fields = ['answer']

questions/views.py
import re
import sys

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from static_lint.models import StaticLint
from submission.models import Submission, TimeStarted
from submission.forms import SubmissionForm
from .models import QuestionComposite, SubQuestionComposite
from results.main import run_tests, create_submission
from results.models import Result, Subtest
from django.core import serializers


# Create your views here.
def question_update_view(request, number):
    obj = get_object_or_404(QuestionComposite, number=number)
    sub_objs = obj.subquestioncomposite_set.all()

    timestamp_first_submission()

    fords = {}

    yo = {}
    static_error = {}

    if request.method == "POST":
        request_dict = request.POST.dict()
        for key, value in request_dict.items():
            answer_key = re.match(r'\d+-answer', key)
            if answer_key:
                first_letter = int(key[0])

                for sub_obj in sub_objs:
                    if first_letter == sub_obj.part:
                        submission = create_submission(number, first_letter)
                        form = SubmissionForm(request.POST or None, instance=submission, prefix=str(first_letter))
                        form_answer = request.POST.get(key)
                        if form.is_valid():
                            form.save()
                            x = get_object_or_404(QuestionComposite, number=number).subquestioncomposite_set.get(
                                part=first_letter)
                            fords[x] = form
                            run_tests(form_answer, number, first_letter, submission)
                    else:
                        submission = Submission.objects.get_last_submission(sub_obj)
                        fords[sub_obj] = SubmissionForm(None, instance=submission, prefix=int(sub_obj.part))
    else:
        for objz in sub_objs:
            submission = Submission.objects.get_last_submission(objz)
            fords[objz] = SubmissionForm(None, instance=submission, prefix=int(objz.part))

    for objz in sub_objs:
        last_submission = Submission.objects.get_last_submission(objz)
        if (hasattr(last_submission, 'staticlint')):
            static_error[objz] = last_submission.staticlint
        else:
            static_error[objz] = None
        yo[objz] = Result.objects.filter(question_number=number, question_part=objz.part, submission=last_submission)
    context = {
        'form': fords,
        'next_question': None,
        'previous_question': None,
        'static_errors': static_error,
        'test_results': yo,
        'question': obj,
        'mark': Result.objects.total_mark_for_question(question_number=number),
    }
    return render(request, "question/questions.html", context)


def timestamp_first_submission():
    time_obj = TimeStarted.objects.get_or_none()
    if not time_obj:
        time = TimeStarted()
        time.save()


def question_list_view(request):
    queryset = QuestionComposite.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, "question/question_list.html", context)


def question_generate_submission_file_view(request):
    filename = generate_filename()

    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename={filename}.txt'

    objects_to_save = [
        TimeStarted.objects.all(),
        QuestionComposite.objects.all(),
        SubQuestionComposite.object.all(),
        Submission.objects.all(),
        StaticLint.objects.all(),
        Result.objects.all(),
        Subtest.objects.all()
    ]

    lines = [serialize(objects) for objects in objects_to_save]
    response.writelines(lines)
    return response


def generate_filename():
    pattern = re.compile(r'(python-marker\d{6})')

    filename = 'python-marker'
    for arg in sys.argv:
        match = pattern.search(arg)
        if match:
            filename = match.group(1)
    return filename


def serialize(object):
    return serializers.serialize("yaml", object)

questions/templates/question/question_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Automated Python Marker</h1>
    <p>Hello thank you for participating</p>
        <p>Please:</p>
        <ul>
            <li>
                Spend at most <b>30 minutes</b> answering the question
            </li>
            <li>
                Upload your answers to the website when you are finished (details are at the bottom of the next page)
            </li>
            <li>
                Remember I am testing the tool, not you! So please submit your answers, they will be anonymous and gratefully received
            </li>
        </ul>

    {% for instance in object_list %}
        <p><a href='{{ instance.get_absolute_url }}'>Click here to get started!</a></p>
    {% endfor %}
{% endblock %}

questions/templates/question/question_update.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block content %}
    <form method='POST' class="lll"> {% csrf_token %}
        <p>{{ object.description | safe }}</p>
        {{ form.as_p }}
        <input type="submit" value="Run Tests & Save"/>
    </form>
{% endblock %}

questions/templates/question/question_yo.html
{% extends 'base.html' %}

{% block content %}

{% include "question/question_update.html" with object=object %}
{% include "static_lint/static_lint_detail_view.html" with object=static_errors %}
{% include "results_view.html" with results=test_results %}
{% include "question/navigate_questions.html" with next_question=next_question previous_question=previous_question %}

<a href="{% url 'questions:question-list' %}">All Questions</a>

{% endblock %}

questions/templates/question/questions.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block content %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
      $(function(){
        $("#hello_button").click(function(e){
            doWork()
            e.preventDefault()
        });

        function doWork() {
            $.ajax({ // create an AJAX call...
                data: {'1-answer': $('textarea[name="1-answer"]').val()},
                headers:{"X-CSRFToken": '{{ csrf_token }}'},// get the form data
                type: 'POST', // GET or POST
                async: false,
                url: '/questions/1/', // the file to call
                success: function (response) { // on success..// update the DIV
                },
            });
            sleep(300)
            $.ajax({ // create an AJAX call...
                data: {'2-answer': $('textarea[name="2-answer"]').val()},
                headers:{"X-CSRFToken": '{{ csrf_token }}'},// get the form data
                type: 'POST', // GET or POST
                async: false,
                url: '/questions/1/', // the file to call
                success: function (response) { // on success..
                },
            });
            sleep(300)
            $.ajax({ // create an AJAX call...
                data: {'3-answer': $('textarea[name="3-answer"]').val()},
                headers:{"X-CSRFToken": '{{ csrf_token }}'},// get the form data
                type: 'POST', // GET or POST
                async: false,
                url: '/questions/1/', // the file to call
                success: function (response) { // on success..
                },
            });
        }

      function sleep(milliseconds) {
          const date = Date.now();
          let currentDate = null;
          do {
            currentDate = Date.now();
          } while (currentDate - date < milliseconds);
      }
     });
    </script>

    <h1>Question {{ question.number }}</h1>
    {{ question.description }}
    <div>.</div>
    <div>
        <b>Note:</b> click the 'Run Tests & Save' buttons to save your work and see how you are doing - do click this
        to save your answer before working on another part
    </div>
    {% for obj, form_instance in form.items %}
        {%  if form|is_composite_question %}
            <h2>{{ obj.part|get_roman_numeral }}) {{ obj.part_name }} [{{ obj.max_mark }} Marks]</h2>
        {% endif %}
        {% include "question/question_update.html" with object=obj form=form_instance %}
        {% include "static_lint/static_lint_detail_view.html" with object=static_errors|get_item:obj %}
        {% include "results_view.html" with results=test_results|get_item:obj marks_available=obj.max_mark %}
    {% endfor %}

    <h3>Total marks</h3>
    {{ test_results|get_total_marks }} / {{ test_results|get_total_available_marks }}

    <h1>Finished?</h1>
    <p>To submit your answers please:</p>
    <ol>
        <li>
            Click this button to save your answers -> <button id="hello_button">Save your answers</button>
        </li>
        <li>
            Please wait for 5 seconds for your answers to be saved
        </li>
        <li>
            Click the link to generate a download file -> <a id='submit_page' href="{% url 'questions:question-submit' %}">Click here to download file</a>
        </li>
        <li>
            Upload the file to the website -> <a href="https://emhodges.github.io/markerWebsite/upload">
            Click here to upload file</a>
        </li>
    </ol>
    <p>Thank you!</p>
{% endblock %}